matrix:
  include:
  - name: "Windows installer"
    os: windows
    language: shell
    before_install:
    - choco install msys2
    - "ls C:/tools/msys64"
    - "dir C:/tools/msys64"
    script: kill 0
    cache:
      directories:
      - C:\tools
