matrix:
  include:
  - name: "Windows installer"
    os: windows
    language: shell
    before_install:
    - choco install python3
    script:
    - python -c "print('Hello World!')"
    cache:
      directories:
      - C:\Python37
