matrix:
  include:
  - name: "Windows installer"
    os: windows
    language: shell
    before_install:
    - choco install msys2
    - C:\tools\msys64\pacman --help
    script:
    - echo Hello World
