matrix:
  include:
  - name: "Windows installer"
    os: windows
    language: shell
    before_install:
    - choco install msys2
    - ls C:\tools\msys64
    - dir C:\tools\msys64
    pacman -S mingw-w64-x86_64-python3-gobject
    cache:
      directories:
      - C:\tools
